### ISSUE TITLE
Viewer es vs cjs imports

### ISSUE THREAD

**Issue by muteor** [wix/ricos#1204]
When doing imports like:

```
import { pluginLinkButton } from 'wix-rich-content-plugin-button/dist/module.viewer';
```

This fails for me on SSR and we have to switch to:

```
import { pluginLinkButton } from 'wix-rich-content-plugin-button/dist/module.viewer.cjs';
```

While this workaround works, it does mean that webpack cannot shake the cjs module. It would be better if the import was like:

```
import { pluginLinkButton } from 'wix-rich-content-plugin-button/dist/viewer';
```

Where `viewer` is a directory that includes a package.json file that has main and module defined. Node and webpack can then choose the correct one for themselves.

Something like:

```
{
  "private": true,
  "main": "../module.viewer.cjs.js",
  "module": "../module.viewer.js"
}
```

**Comment by lxgreen** [comment]
fixed
