### ISSUE TITLE
setState call after unmount

### ISSUE THREAD

**Issue by muteor** [wix/ricos#121]
I see warning:

```Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.```

This is due to https://github.com/wix-incubator/rich-content/blob/master/packages/editor/src/RichContentEditor/Toolbars/SideToolbar/SideToolbar.jsx#L65

Probably need to track mounted status and check that inside the async call.

**Comment by lxgreen** [comment]
cannot reproduce
