### ISSUE TITLE
Toolbar toggle buttons isActive should be used on initial render

### ISSUE THREAD

**Issue by muteor** [wix/ricos#174]
In our gallery component we have a limited set of grids, and UX want single "toggle" buttons for each setting instead of a dropdown:

![image](https://user-images.githubusercontent.com/305164/47645063-cea78680-db67-11e8-887b-2377f6e0d568.png)

Currently the active button is only active after click, we would like it to handle the state from the initial component state.

Something similar to how dropdown does it with `getValue` would be great:

```
{
      keyName: 'layout',
      type: BUTTONS.DROPDOWN,
      options: galleryLayoutsDropdown(t),
      onChange: switchLayout,
      getValue: getCurrentLayout,
      mobile: true,
    },
```

**Comment by lxgreen** [comment]
to be fixed within toolbar externalization
