### ISSUE TITLE
Bug: Preview exceeds iframe width on Instagram link previews

### ISSUE THREAD

**Issue by gbrgrc** [wix/ricos#2433]
When displaying an Instagram link preview, the border on the right is hidden:

<img width="696" alt="Screen Shot 2021-05-03 at 11 27 12" src="https://user-images.githubusercontent.com/50117428/116889528-0c873900-ac03-11eb-9218-e2f72b23d2ce.png">

This seems to be caused by [this line](https://github.com/wix/ricos/blob/7fbb16c5b63a7f0e311f36fb620ad9f386f324ab/packages/plugin-html/web/src/htmlIframeSrc.ts#L22) overriding [this one](https://github.com/wix/ricos/blob/7fbb16c5b63a7f0e311f36fb620ad9f386f324ab/packages/plugin-html/web/src/htmlIframeSrc.ts#L9) as seen on dev tools:

<img width="801" alt="Screen Shot 2021-05-03 at 11 27 43" src="https://user-images.githubusercontent.com/50117428/116889457-f6797880-ac02-11eb-9061-04024b9a5240.png">

**Comment by danarish4** [comment]
Fixed on v8.33.1
